- .github/action/operator-sdk/Dockerfile
- .github/action/operator-sdk/entrypoint.sh
- .github/workflows/ci.yaml
- .github/workflows/master.yaml
- .github/workflows/release.yaml
Fixes https://github.com/humio/humio-operator/issues/46
> Run operator-sdk ci, publish image on push to master and tag/push on release

- pkg/apis/core/v1alpha1/humiocluster_types.go
- pkg/controller/humiocluster/configmaps.go
- pkg/controller/humiocluster/defaults.go
- pkg/controller/humiocluster/humiocluster_controller.go
- pkg/controller/humiocluster/humiocluster_controller_test.go
- pkg/controller/humiocluster/pods.go
Resolves: https://github.com/humio/humio-operator/issues/49
> Add extra kafka configs configmap

- go.mod
- pkg/controller/humiocluster/humiocluster_controller.go
- pkg/controller/humiocluster/metrics.go
- pkg/controller/humioingesttoken/humioingesttoken_controller.go
- pkg/controller/humioingesttoken/metrics.go
A bit more refactoring of the metrics. There is some duplication between the humiocluster metrics and humioingesttoken metrics, though I'm not sure there will be a lot more duplication going forward.
> Refactor metrics

- README.md
- deploy/crds/core.humio.com_humioclusters_crd.yaml
Added some basic installation docs as well as the imagePullPolicy crd which was missed.
> Update manual install docs

- examples/eks-simple-cluster/README.md
- examples/eks-simple-cluster/humio-cluster-simple.yml
- examples/eks-simple-cluster/humio-load-balancer.yml
- examples/eks-simple-cluster/humio-operator.yml
> Procedural directions to install the operator

- examples/eks-simple-cluster/README.md
I believe we should add the namespace to clusterole as well based on testing. This also adds documentation regarding changing the namespace in the eks example.
> Namespace addition for cluster role and doc update

- deploy/cluster_role_openshift.yaml
- deploy/cluster_scc_openshift.yaml
- examples/eks-simple-cluster/README.md
- examples/eks-simple-cluster/humio-operator.yml
Let me know if you think the openshift files should be elsewhere.
> Add openshift specifics, update docs

- README.md
- deploy/crds/core.humio.com_v1alpha1_humiocluster_cr.yaml
- examples/eks-simple-cluster/humio-cluster-simple.yml
- examples/eks-simple-cluster/humio-load-balancer.yml
- examples/ephemeral-with-s3-storage.yaml
- examples/nginx-ingress-with-cert-manager.yaml
- hack/restart-k8s.sh
- pkg/controller/humiocluster/defaults.go
- pkg/controller/humiocluster/humiocluster_controller_test.go
- pkg/controller/humiocluster/pods.go
- pkg/kubernetes/kubernetes.go
These are probably not all we need, but it's a start.
> Add common annotations and labels

- charts/humio-operator/templates/operator-deployment.yaml
- charts/humio-operator/templates/operator-rbac.yaml
- cmd/manager/main.go
- go.mod
- go.sum
- hack/install-zookeeper-kafka-crc.sh
- hack/run-e2e-tests-crc.sh
- hack/run-e2e-tests-kind.sh
- hack/test-helm-chart-crc.sh
- pkg/controller/humiocluster/humiocluster_controller.go
- pkg/helpers/helpers.go
- pkg/openshift/security_context_constraints.go
@schofield @jswoods Please note the comment I added here: https://github.com/humio/humio-operator/pull/99/files#diff-ce7c48c375529121a664eed29178b5a3R154-R158
Let me know if you think we should move to finalizers right away, or if this is sufficient for the time being.
> Install SCC on Helm chart installation and add/remove service accounts from it as needed.

- .github/action/operator-sdk/Dockerfile
- pkg/controller/humiocluster/humiocluster_controller.go
Let me know if you know of a good way to test this. I couldn't come up with anything simple. I suppose we could have it in part of the e2e tests but I'm not sure if that's really where we should be putting it?
I did test it manually and confirmed it fixes https://github.com/humio/humio-operator/issues/115.
> Fix delete bad pod

- deploy/crds/core.humio.com_humioclusters_crd.yaml
- examples/ephemeral-with-gcs-storage.yaml
- pkg/apis/core/v1alpha1/humiocluster_types.go
- pkg/controller/humiocluster/defaults.go
- pkg/controller/humiocluster/humiocluster_controller_test.go
- pkg/controller/humiocluster/pods.go
Fixes https://github.com/humio/humio-operator/issues/117
> Support additional humio volume mounts and pod volumes

- .github/workflows/ci.yaml
- .github/workflows/release-container-helperimage.yaml
- .github/workflows/release-container-image.yaml
- build/Dockerfile
- images/helper/Dockerfile
Adds labels and licenses to the Docker images for certification compliance.
Adds addition workflow steps to push the images to the Redhat container scanner registry.
> Adds labels and workflow additions for Redhat certification

- .github/workflows/release-container-helperimage.yaml
Fixes license copy for RH certificattion.
> Fix license copy

- .github/workflows/master.yaml
Master needed license copy as well.
> Fix helper master build

- charts/humio-operator/templates/crds.yaml
- deploy/crds/core.humio.com_humioclusters_crd.yaml
- hack/run-e2e-tests-crc.sh
- hack/run-e2e-tests-kind.sh
- pkg/apis/core/v1alpha1/humiocluster_types.go
- pkg/controller/humiocluster/defaults.go
- pkg/controller/humiocluster/humiocluster_controller.go
- pkg/controller/humiocluster/humiocluster_controller_test.go
- pkg/controller/humiocluster/ingresses.go
- pkg/controller/humiocluster/services.go
- pkg/kubernetes/services.go
- test/e2e/humiocluster_test.go
- test/e2e/humiocluster_with_tls_test.go
Fixes https://github.com/humio/humio-operator/issues/113 and also exposes overriding ports for the service.
> Expose options for humio service type and ports

- .github/workflows/release-container-helperimage.yaml
- .github/workflows/release-container-image.yaml
- images/helper/version.go
Fix RH_SCAN_OSPID reference in actions.
>  Bump helper version to 0.0.5

- .github/workflows/release-container-helperimage.yaml
- .github/workflows/release-container-image.yaml
- images/helper/version.go
Fix env location for tag and push for RH_SCAN
> Bump helper version to 0.0.7

- .github/workflows/release-container-image.yaml
- deploy/crds/core.humio.com_humioclusters_crd.yaml
- deploy/crds/core.humio.com_humioexternalclusters_crd.yaml
- deploy/crds/core.humio.com_humioingesttokens_crd.yaml
- deploy/crds/core.humio.com_humioparsers_crd.yaml
- deploy/crds/core.humio.com_humiorepositories_crd.yaml
- deploy/olm-catalog/humio-operator/humio-operator.package.yaml
- version/version.go
Will need a helm release as it wasn't bumped in the 0.0.7
Fixes RH Scan for operator as well
> Release 0.0.8

- pkg/apis/core/v1alpha1/humiocluster_types.go
- pkg/controller/humiocluster/defaults.go
- pkg/controller/humiocluster/humiocluster_controller.go
- pkg/controller/humiocluster/humiocluster_controller_test.go
- pkg/helpers/helpers.go
- test/e2e/humiocluster_bootstrap_test.go
- test/e2e/humiocluster_restart_test.go
- test/e2e/humiocluster_upgrade_test.go
- test/e2e/humiocluster_with_tls_test.go
Currently if nodeCount is set to zero then it is reset back to 3, which is the default. This fixes this problem by making nodeCount a pointer.
> Make nodeCount a pointer so it can be set to zero

- charts/humio-operator/Chart.yaml
- charts/humio-operator/README.md
- charts/humio-operator/values.yaml
- deploy/crds/core.humio.com_humioclusters_crd.yaml
- deploy/crds/core.humio.com_humioexternalclusters_crd.yaml
- deploy/crds/core.humio.com_humioingesttokens_crd.yaml
- deploy/crds/core.humio.com_humioparsers_crd.yaml
- deploy/crds/core.humio.com_humiorepositories_crd.yaml
- version/version.go
Depends on https://github.com/humio/humio-operator/pull/149.
> Release helm chart 0.0.11

- pkg/controller/humiocluster/humiocluster_controller.go
Fixes #148 
This should prevent us from deleting Certificates owned by Ingress objects.
Also, ignore TLS secrets which is not of type Issuer as all node-to-node
communication uses that. Similarly, all our node-to-node certificates
has empty common-name annotations so skip the secrets that do not match
this.
> Only clean up TLS certificates with HumioCluster as owner.

- .github/workflows/ci.yaml
- .github/workflows/master.yaml
- .github/workflows/release-container-helperimage.yaml
- .github/workflows/release-container-image.yaml
- Makefile
Initially I just wanted to add it as part of https://github.com/humio/humio-operator/pull/171 but that PR still needs debugging, so let's just merge this fix separately.
> Update workflows to support additional build args.

- api/v1alpha1/humiocluster_types.go
- charts/humio-operator/templates/crds.yaml
- config/crd/bases/core.humio.com_humioclusters.yaml
- controllers/humiocluster_controller.go
- controllers/humiocluster_controller_test.go
- controllers/humiocluster_defaults.go
- controllers/humiocluster_metrics.go
- controllers/humiocluster_pods.go
- pkg/kubernetes/configmaps.go
Fixes https://github.com/humio/humio-operator/issues/158
> Add property to configure view-group-permissions.json

- controllers/humiocluster_controller_test.go
- controllers/humiocluster_pods.go
Depends on https://github.com/humio/humio-operator/pull/186 and https://github.com/humio/humio-operator/pull/193
> Add test to cover HumioCluster configured in multi-org mode.

- hack/run-e2e-tests-crc.sh
- hack/run-e2e-tests-kind.sh
- hack/start-crc-cluster.sh
- hack/start-kind-cluster.sh
Code has already been updated to look for the stable label, if not found, look for the deprecated beta label.
Fixes #201
> Use stable zone label for tests

- controllers/humiocluster_controller.go
- controllers/humiocluster_controller_test.go
- images/helper/main.go
- pkg/kubernetes/pods.go
Fixes part of https://github.com/humio/humio-operator/issues/163.
> Fix bug where service account secrets are not created when using custom service accounts and add tests

- charts/humio-operator/Chart.yaml
- charts/humio-operator/values.yaml
- config/crd/bases/core.humio.com_humioclusters.yaml
- config/crd/bases/core.humio.com_humioexternalclusters.yaml
- config/crd/bases/core.humio.com_humioingesttokens.yaml
- config/crd/bases/core.humio.com_humioparsers.yaml
- config/crd/bases/core.humio.com_humiorepositories.yaml
Depends on: https://github.com/humio/humio-operator/pull/225
> Release helm chart 0.1.0

- charts/humio-operator/templates/operator-deployment.yaml
- charts/humio-operator/values.yaml
Fixes https://github.com/humio/humio-operator/issues/229
> Make resource settings for the operator container adjustable by the user

- charts/humio-operator/Chart.yaml
The main purpose for this is to release a helm chart version which includes https://github.com/humio/humio-operator/pull/231
> Bump helm chart version

- controllers/humiocluster_controller.go
- controllers/humiocluster_controller_test.go
Fixes https://github.com/humio/humio-operator/issues/212
> Skip ES ingress if no hostname is specified

- charts/humio-operator/templates/operator-service.yaml
- charts/humio-operator/templates/operator-servicemonitor.yaml
- charts/humio-operator/values.yaml
> Add ServiceMonitor for operator

- hack/run-e2e-tests-kind.sh
#232 should be merged before this PR - when that happens I'll rebase this PR
> Extract humio images from go source

- controllers/humiocluster_controller.go
- controllers/humiocluster_persistent_volumes.go
Fixes https://github.com/humio/humio-operator/issues/245.
> Wait for new PVCs rather than sleeping

- api/v1alpha1/humiocluster_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- controllers/humiocluster_controller_test.go
- controllers/humiocluster_defaults.go
- controllers/humiocluster_pods.go
- examples/humiocluster-affinity-and-tolerations.yaml
Fixes https://github.com/humio/humio-operator/issues/248.
> Add tolerations for humio pods

- .github/workflows/chart-lint.yaml
- .github/workflows/e2e.yaml
- controllers/humiocluster_controller.go
- controllers/humiocluster_controller_test.go
- controllers/humiocluster_defaults_test.go
- controllers/humioresources_controller_test.go
- pkg/helpers/helpers.go
- pkg/kubernetes/cluster_role_bindings.go
- pkg/kubernetes/cluster_roles.go
- pkg/kubernetes/configmaps.go
- pkg/kubernetes/ingresses.go
- pkg/kubernetes/kubernetes.go
- pkg/kubernetes/persistent_volume_claims.go
- pkg/kubernetes/pods.go
- pkg/kubernetes/role_bindings.go
- pkg/kubernetes/roles.go
- pkg/kubernetes/secrets.go
- pkg/kubernetes/service_accounts.go
- pkg/kubernetes/services.go
Nothing major. Fixes godoc, typos, ineffective assignment.
Most of the godoc seems slightly awkward to add though as the function names are already fairly self-explanatory.
Also noticed we had a duplicate function used for obtaining labels for both pods and PVC's, so I merged them together.
> Fix a few things highlighted by Go Report Card.

- controllers/humiocluster_controller.go
The goal is to improve the stability of restarts and updates as we are seeing some test flakiness possibly due to ignoring the failed updates to the humiocluster's status.
> Return errors and re-run reconcile when status updates fail on the humiocluster resource

- charts/humio-operator/templates/operator-rbac.yaml
- charts/humio-operator/values.yaml
Fixes https://github.com/humio/humio-operator/issues/275.
> Add helm value for opting out of managing role and cluster role resources

- .github/workflows/release-container-helperimage.yaml
- .github/workflows/release-container-image.yaml
- controllers/humiocluster_controller_test.go
- controllers/suite_test.go
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> Replace set-env with use of environment file

- images/helper/main.go
This branch builds on top of the changes in this PR: https://github.com/humio/humio-operator/compare/mike/validate_method_for_obtaining_api_token?expand=1
My plan is to get this PR merged, release a new helper image, then update a PR for the other branch which will also start using the new helper image.
> helper: Add annotation indicating how API token was obtained

- controllers/humiocluster_controller.go
Fixes https://github.com/humio/humio-operator/issues/224
> Cleanup CA Issuer when TLS is disabled

- controllers/humioresources_controller_test.go
... even if it did not create the cluster for the specific test case.
Right now we create the `HumioCluster` if it doesn't exist, but if it
already was created, we start the test case immediately. Instead we
should be waiting for the cluster to enter Running state.
> Tests using shared cluster should wait for Running cluster state

- controllers/humioresources_controller_test.go
The main purpose here is to make it easier to run these tests in
parallel. It also has the added benefit of making it easier to create
and cleanup the shared HumioCluster resource.
---
I did start on running the test cases in parallel without this change, but ran into a bunch of problems with that. This new structure is slightly less readable, and ideally we would split it up again. I'm thinking we can live with this for now if it means parallelizing all our "test specs" will be much easier.
> Merge "humio resources tests" to a single test spec.

- controllers/humiocluster_controller.go
- controllers/humiocluster_controller_test.go
- controllers/humiocluster_pod_status.go
- controllers/humiocluster_pod_status_test.go
- controllers/humiocluster_pods.go
Fixes https://github.com/humio/humio-operator/issues/210
> Cleanup pods that are unable to start by deleting them during subsequent upgrades or restarts

- controllers/humiocluster_controller.go
- controllers/humiocluster_controller_test.go
Fixes: https://github.com/humio/humio-operator/issues/301
> Mark cluster as ConfigError if any of the referenced service accounts do not exist.

- api/v1alpha1/humioingesttoken_types.go
- api/v1alpha1/humioparser_types.go
- api/v1alpha1/humiorepository_types.go
- api/v1alpha1/humioview_types.go
- config/samples/core_v1alpha1_humiocluster.yaml
- config/samples/core_v1alpha1_humiocluster_shared_serviceaccount.yaml
- controllers/humiocluster_controller.go
- controllers/humiocluster_status.go
- controllers/humioexternalcluster_controller.go
- controllers/humioexternalcluster_status.go
- controllers/humioingesttoken_controller.go
- controllers/humioparser_controller.go
- controllers/humiorepository_controller.go
- controllers/humioresources_controller_test.go
- controllers/humioview_controller.go
- examples/humiocluster-ephemeral-with-gcs-storage.yaml
- examples/humiocluster-ephemeral-with-s3-storage.yaml
- examples/humiocluster-persistent-volumes.yaml
- pkg/humio/client.go
- pkg/humio/client_mock.go
> Add ConfigError to all resource types

- controllers/humiocluster_controller_test.go
- controllers/humiocluster_defaults.go
Fixes: https://github.com/humio/humio-operator/issues/320
> Ensure replication factor environment variables are set to use suggested partition layouts.

- charts/humio-operator/templates/operator-rbac.yaml
Fixes: https://github.com/humio/humio-operator/issues/347
> Add missing permissions for new CRD's in Helm chart

- Makefile
- api/v1alpha1/humiocluster_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- charts/humio-operator/templates/crds.yaml
- config/crd/bases/core.humio.com_humioclusters.yaml
- controllers/humiocluster_controller_test.go
- controllers/humiocluster_defaults.go
- controllers/humiocluster_pods.go
Behavior is like follows:
- If not specified: use default probes.
- If specified and non-empty: use user-defined probes.
- If specified and empty: do not use any probes.
> Configurable Humio container probes

- controllers/humiocluster_controller.go
- controllers/humiocluster_controller_test.go
Fixes https://github.com/humio/humio-operator/issues/361
> Ensure operator resets humiocluster state when all pods are healthy

- .github/workflows/e2e.yaml
- hack/start-kind-cluster.sh
Stick with same k8s minor versions for now
> Bump kind to latest version

- .github/workflows/ci.yaml
- controllers/humioalert_annotations.go
- controllers/humiocluster_controller.go
- controllers/humiocluster_tls.go
- controllers/humioingesttoken_controller.go
- images/helper/main.go
- main.go
- pkg/helpers/helpers.go
- pkg/humio/client_mock.go
- pkg/kubernetes/kubernetes.go
- pkg/kubernetes/secrets.go
More info here: https://github.com/securego/gosec
> Run gosec on CI

- api/v1alpha1/humiocluster_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- charts/humio-operator/templates/crds.yaml
- config/crd/bases/core.humio.com_humioclusters.yaml
- controllers/humiocluster_controller_test.go
- controllers/humiocluster_defaults.go
- controllers/humiocluster_pods.go
Fixes https://github.com/humio/humio-operator/issues/427.
> Add startup probe support

- controllers/humiocluster_annotations.go
> Fix panic in incrementHumioClusterPodVersion

- controllers/humiocluster_controller.go
- controllers/humiocluster_controller_test.go
- controllers/humiocluster_services.go
Fixes https://github.com/humio/humio-operator/issues/510
> Add support for updating service and headless service labels, annotations and selector

- controllers/humiocluster_controller.go
- controllers/humiocluster_controller_test.go
- controllers/humiocluster_pod_status.go
Fixes both https://github.com/humio/humio-operator/issues/512 and https://github.com/humio/humio-operator/issues/533
> Allow deletion of pods that are evicted or pending

- controllers/humiocluster_controller.go
Fixes: https://github.com/humio/humio-operator/issues/551
> Should return early if we are unable to obtain humio version from string

- .github/workflows/e2e.yaml
- controllers/suite/clusters/humiocluster_controller_test.go
- controllers/suite/clusters/suite_test.go
- controllers/suite/common.go
- controllers/suite/resources/suite_test.go
- go.sum
- hack/run-e2e-tests-using-kubectl-kind.sh
Depends on https://github.com/humio/humio-operator/pull/556.
> Add docker registry credentials to humio pods for e2e tests

- README.md
To route correctly following the Library update on Jul 13.
> Update Humio Library Links

- controllers/humiocluster_version.go
- controllers/humiocluster_version_test.go
> HumioVersionFromString should strip away SHA pin

- api/v1alpha1/humiocluster_types.go
- charts/humio-operator/crds/core.humio.com_humioclusters.yaml
- config/crd/bases/core.humio.com_humioclusters.yaml
- controllers/humiocluster_defaults.go
- controllers/humiocluster_pods.go
- controllers/suite/clusters/humiocluster_controller_test.go
Fixes https://github.com/humio/humio-operator/issues/596.
> Add support for custom PriorityClass on humio pods

- .github/workflows/release-container-image.yaml
- charts/humio-operator/Chart.yaml
Fixes https://github.com/humio/humio-operator/issues/700
> Add link to upgrade notes

- controllers/humiocluster_controller.go
Without this, we end up calculating an env var source hash of only the first entry we see, so if we have multiple of them, this would not include everything and thus not end up with a new hash - which would otherwise mean pods would've been replaced.
> Include all env var sources when getting env var sources

- controllers/humiocluster_controller.go
- controllers/humiocluster_defaults.go
- controllers/suite/clusters/humiocluster_controller_test.go
- controllers/suite/common.go
* Don't create services on empty node pool
* Clean up services that were created but now no longer have a backing node pool
> Don't create unused resources on empty node pool

- controllers/humiocluster_controller.go
> Fix bad error msg in humiocluster_controller.go

- api/v1alpha1/humiocluster_types.go
- charts/humio-operator/crds/core.humio.com_humioclusters.yaml
- config/crd/bases/core.humio.com_humioclusters.yaml
- controllers/suite/clusters/humiocluster_controller_test.go
- controllers/suite/resources/humioresources_controller_test.go
This seems to be the main cause of the flaky test results we have.
> Set rolling update for env var update test

- controllers/humioparser_controller.go
- controllers/suite/resources/humioresources_controller_test.go
- go.mod
- go.sum
- pkg/humio/client.go
- pkg/humio/client_mock.go
Depends on https://github.com/humio/cli/pull/161
> Use LogScale parsers v2 API

- controllers/suite/clusters/humiocluster_controller_test.go
https://github.com/humio/humio-operator/actions/runs/9527911961/job/26265060272
```
[FAILED] in [It] - /var/src/controllers/suite/clusters/humiocluster_controller_test.go:4897 @ 06/15/24 12:47:40.583
<< Timeline
[FAILED] Expected success, but got an error:
<*errors.StatusError | 0xc001662b40>:
Operation cannot be fulfilled on pods "humiocluster-nodepool-labels-core-kufsfk": the object has been modified; please apply your changes to the latest version and try again
{
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "Operation cannot be fulfilled on pods \"humiocluster-nodepool-labels-core-kufsfk\": the object has been modified; please apply your changes to the latest …
```
> Retry pod update during test

- go.mod
- internal/controller/humiocluster_controller.go
- internal/controller/humiocluster_controller_test.go
> Removed duplicated entries of an environment variable

- internal/controller/humiocluster_pod_lifecycle.go
This is a follow up to https://github.com/humio/humio-operator/pull/857.
It is not exactly the proposed change in
https://github.com/humio/humio-operator/pull/857 but the goal is overall the same.
> Make RollingUpdateBestEffort behave more like RollingUpdate

- internal/controller/humiocluster_pod_lifecycle.go
Fixes https://github.com/humio/humio-operator/issues/992
> Fix nil pointer when using update strategy RollingUpdateBestEffort

- api/v1alpha1/humiocluster_types.go
- charts/humio-operator/crds/core.humio.com_humioclusters.yaml
- config/crd/bases/core.humio.com_humioclusters.yaml
- docs/api.md
Fixes https://github.com/humio/humio-operator/issues/1000
> Fix PDB field validation issue
