pkg/controller/humiocluster/humiocluster_controller.go
pkg/controller/humiocluster/humiocluster_controller_test.go

Nothing major here, just tidying up what was highlighted by https://goreportcard.com/report/github.com/humio/humio-operator#ineffassign

Clean up ineffectual assignments

---

pkg/controller/humiocluster/defaults.go
pkg/controller/humiocluster/humiocluster_controller.go
pkg/controller/humiocluster/pods.go

This should help with cases where there are mutating webhooks which
makes it difficult to compare the actual pod spec vs desired pod spec.

Refactor the way we determine if pod spec changed

---

pkg/controller/humiocluster/pods.go
test/e2e/bootstrap_test.go
test/e2e/humiocluster_test.go
test/e2e/ingest_token_test.go
test/e2e/parser_test.go
test/e2e/repository_test.go

I was trying to structure this a little more, while also making tests not run serially. There is probably more we can do on that front especially as we add tests for other clusters.
I'm not sure how we want to handle timeouts. Right now we're using the global timeout of 5 minutes for each test Wait(). But I'm thinking we could probably wait indefinitely in each one so long as it is clear where it timed out.
Not really sure if this is what we want which is why I have it as draft status.

Refactor e2e tests

---

pkg/controller/humiocluster/defaults.go
pkg/controller/humiocluster/humiocluster_controller.go
pkg/controller/humiocluster/humiocluster_controller_test.go
pkg/controller/humiocluster/pods.go
pkg/kubernetes/configmaps.go

This moves us one step closer to closing https://github.com/humio/humio-operator/issues/92
This fixes the problems with resource name conflicts when handling
multiple HumioCluster resources in the same namespace.
This breaks the `crc` cluster things for now, because we cannot pre-populate the service account names in the `users` property in the `SecurityContextConstraint` resource, because service accounts are now named based on the CR names. I'm thinking we should just merge this anyway because #92 already contains a step to fix the SCC issues. Let me know if you think the SCC changes needs to be done in this PR, then I'll update it, if not, then I will take a look at this in a followup PR.

Refactor naming of k8s resources created for a HumioCluster.

---

charts/humio-operator/README.md
charts/humio-operator/templates/operator-deployment.yaml
charts/humio-operator/templates/operator-rbac.yaml
charts/humio-operator/values.yaml
cmd/manager/main.go

This builds on top of https://github.com/humio/humio-operator/pull/97 and moves us yet another step closer to closing #92
~I was hoping it was as simple as creating a pair of `Role` & `RoleBinding` resources for each namespace we want to watch and then set the `WATCH_NAMESPACE` for the Humio operator to be a comma-separated list, but that doesn't seem like the case. The operator doesn't accept a comma-separated list in `WATCH_NAMESPACE`. Here's an example of the output when trying to pass on multiple namespaces:~
~`
E0611 13:09:04.316750       1 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *v1alpha1.HumioExternalCluster: humioexternalclusters.core.humio.com is forbidden: User …

Refactor helm chart to allow watching a single, multiple or all namespaces

---

.github/workflows/chart-lint.yaml
.github/workflows/master.yaml
.github/workflows/release-container-image.yaml
.github/workflows/release-helm-chart.yaml
README.md

Fixes #89 
- Trigger release processes based on version number changes instead of git tags
- Drop `v` prefix from version numbers of container images
- Use git tag prefix `operator-` related to releasing container images
- Git tag prefix for releases of helm charts remains to be the name of the chart
- Add container image reference to github release when publishing a new container image

Adjust release process.

---

pkg/controller/humiocluster/humiocluster_controller.go
pkg/controller/humiocluster/humiocluster_controller_test.go
pkg/controller/humiocluster/status.go
test/e2e/humiocluster_with_pvcs_test.go

This appears to fix the race. When testing, it logged:
```
{"level":"info","ts":1594250994.9888318,"caller":"humiocluster/humiocluster_controller.go:1020","msg":"validating new pod was created. expected pod count 1, current pod count 0","Request.Namespace":"humio-operator","Request.Name":"example-humiocluster-pvc","Request.Type":"ReconcileHumioCluster"}
{"level":"info","ts":1594250995.989429,"caller":"humiocluster/humiocluster_controller.go:1020","msg":"validating new pod was created. expected pod count 1, current pod count 1","Request.Namespace":"humio-operator","Request.Name":"example-humiocluster-pvc","Request.Type":"ReconcileHumioCluster"}
```
Note that it appears to take a second or so at least in some cases. With this same change but without the sleep/timeout in the loop, we end up …

Additional logging and fix race with bootstrapping pods

---

deploy/crds/core.humio.com_humioclusters_crd.yaml
pkg/apis/core/v1alpha1/humiocluster_types.go
pkg/controller/humiocluster/annotations.go
pkg/controller/humiocluster/defaults.go
pkg/controller/humiocluster/humiocluster_controller.go
pkg/controller/humiocluster/humiocluster_controller_test.go
pkg/controller/humiocluster/pods.go
test/e2e/humiocluster_restart_test.go
test/e2e/humiocluster_test.go
test/e2e/humiocluster_upgrade_test.go

This adds support for two ways of restarting pods: Restarting and Upgrading. It also introduces the idea of a "pod revision", which allows us to trigger restarts of Humio pods without changing the HumioCluster spec.
When the HumioCluster Spec is changed such that the Humio image is updated, then we change to a cluster state of Upgrading and take down all pods until there are none running, then start them all back up mostly at the same time.
When the HumioCluster Spec is changed in any other way other than updating the image, we change to a cluster state of Restarting and take down one pod at a time, wait for it to become Ready and then move on to the next pod (similar to basic deployments).
If we want to trigger a restart of Humio without changing the spec, we can increment the revision …

Add humio pod restart and upgrade functionality

---

.github/workflows/release-container-helperimage.yaml
.github/workflows/release-container-image.yaml
images/helper/version.go

Changes RH_SCAN references to fix env var usage.

 Bump helper version to 0.0.6

---

pkg/controller/humiocluster/ingresses.go

According to https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#backend-certificate-authentication, we need the format "namespace/secret-name".

Fix issue with ingress proxy-ssl-secret annotation

---

charts/humio-operator/templates/operator-deployment.yaml

When using spinnaker, it sets the label `"app.kubernetes.io/managed-by"`, which then causes the deployment to break due to:
```
Deploy failed: The Deployment "humio-operator" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"humio-operator", "app.kubernetes.io/instance":"humio-operator", "app.kubernetes.io/managed-by":"spinnaker", "app.kubernetes.io/name":"humio-operator"}: selector does not match template labels
```
Once the managed-by label is removed, it works as the selector is no longer using the label, thus it no longer needs to match. I don't think any of these are necessary on the operator deployment? The downside of changing these labels is the deployment will need to be deleted prior to updating to the version of the operator that contains this …

Reduce labels and selector matchLabels that the operator deployment uses

---

charts/humio-operator/README.md

When trying to setup the operator I couldn't get the installation instructions in this readme to work as the chart repo was unknown.
This adds the `helm repo add` command to the installation instructions, which fixed it for me.
It is done the same way as described in https://github.com/humio/humio-operator/blob/master/docs/README.md#optional-prepare-an-installation-of-kafka-and-zookeeper

Add chart repo install instructions

---

controllers/humiocluster_annotations.go
controllers/humiocluster_controller.go
controllers/humiocluster_pods.go
controllers/humiocluster_status.go
controllers/humioexternalcluster_controller.go
controllers/humioingesttoken_controller.go
controllers/humioparser_controller.go
controllers/humiorepository_controller.go
controllers/suite_test.go
go.mod
main.go
pkg/humio/client.go
pkg/humio/cluster.go
pkg/humio/cluster_test.go

Fixes #168 
@jswoods Logs are still identical the old logs, or at least very close to, but at least this way we only define one logger on the reconciler structs.
It is possible we could replace the `logr.Logger` with the `zap.SugaredLogger` on the reconciler's, but the default scaffolding assumes we use `logr.Logger`. Let me know what you think we should do. I'm thinking we should just go with this for now and perhaps refactor this to the other logger later if needed. Personally, I really like the way we log errors with the approach shown in this PR, and I think we log out errors many more places than we do info logs, so perhaps we can live without the old `Infof()` method and such.

Define only one logger on Reconciler structs

---

.github/workflows/master.yaml
.github/workflows/release-container-image.yaml

Looks like "Publish Master" workflow is failing because we reference the olm-catalog which right now doesn't exist.
https://github.com/humio/humio-operator/actions?query=workflow%3A%22Publish+Master%22

Disable olm bundle lint/push as we do not have a bundle at this point

---

controllers/humiocluster_controller.go

zapr expects key/value pairs if we provide additional arguments
following the main message

Small fix for log message

---

.github/workflows/release-container-image.yaml
Makefile

We already run the tests as a separate job in the CI workflow.
Without this change we run tests twice in our CI workflow,
making the CI workflow run for an additional ~3-4 minutes.
I've decided to add a run of our tests as part of releasing a new
operator container image. We could also leave it out, but without
this we could end in situations where not all the relevant changes
have been tested together, mainly in scenarios where we have branches
for a PR that are not up to date with master but passes tests.

Remove dependency on test target for building operator container.

---

controllers/humiocluster_controller.go
controllers/humiocluster_controller_test.go
controllers/humiocluster_pods.go
controllers/humioresources_controller_test.go
go.mod
go.sum
hack/start-crc-cluster.sh
hack/start-kind-cluster.sh

Initially I was adding all the 3 configuration options (in https://github.com/humio/humio-operator/pull/171) to be able to leverage suggested partition layouts, but this causes a few problems at this point. We can however start by just adding the ZONE configuration as a start, then add replication factors later.
The few TODO's I removed are already captured in an issue, so I don't see why we would keep the TODO's around in the code as well: https://github.com/humio/humio-operator/issues/167

Add ZONE configuration option to Humio containers.

---

controllers/humiocluster_pods.go

Some setups can have larger files that will be parsed in the current
implementation of the sidecar. For now, bump memory limit to buy us a
bit of time before migrating completely away from parsing the files.

Bump memory limit for auth sidecar

---

controllers/humiocluster_annotations.go
controllers/humiocluster_controller.go
controllers/humiocluster_pods.go
controllers/humiocluster_tls.go
images/helper/main.go

This way we do not rely on cluster DNS. We can do this
because `/etc/hosts` for the sidecar already contains the
information needed to perform the lookup

sidecar: Drop cluster name and namespace from the hostname

---

charts/humio-operator/templates/operator-rbac.yaml

Helm2 produces an invalid manifest:
```yaml
---apiVersion: v1
kind: ServiceAccount
metadata:
name: 'release-name'
```

fix: helm2 compatibility

---

Dockerfile

Changes USER from nonroot:nonroot to 1001, otherwise breaks RH registry scanning.  Based on other operators using UBI8 base images this seems to be the norm. I don't think there are any negative implications, but maybe the e2e tests will tell us.

Changes USER declaration due to RH scanner error

---

api/v1alpha1/humiocluster_types.go
api/v1alpha1/zz_generated.deepcopy.go
charts/humio-operator/templates/crds.yaml
config/crd/bases/core.humio.com_humioclusters.yaml
config/crd/bases/core.humio.com_humioexternalclusters.yaml
config/crd/bases/core.humio.com_humioingesttokens.yaml
config/crd/bases/core.humio.com_humioparsers.yaml
config/crd/bases/core.humio.com_humiorepositories.yaml
controllers/humiocluster_controller_test.go
controllers/humiocluster_pods.go
pkg/kubernetes/kubernetes.go

This PR adds support for providing user-defined annotations to pods, e.g. injection of linkerd sidecar containers `linkerd.io/inject: enabled` or similar. 
This was my initial stab at adding support for annotations to the humio-core pods. Any feedback on the structure, implementation, etc. is highly appreciated. 
I've used operator-sdk 1.0.1, and the crds doesn't seem to have been updated along with the upgrade to 1.0.1. These were generated in a separate commit, and could be reverted for a simpler diff. 
Let me know how to proceed.
This PR fixes #203.

Add support for additional annotations to Pods

---

api/v1alpha1/humiocluster_types.go
charts/humio-operator/templates/crds.yaml
config/crd/bases/core.humio.com_humioclusters.yaml
controllers/humiocluster_controller_test.go
controllers/humiocluster_defaults.go
controllers/humiocluster_ingresses.go

This is useful if you rely on e.g. AWS NLB's for doing TLS termination,
while the NLB is communicating to ingress-nginx over unencrypted communications.
By default, we will stick to the assumption that TLS should be enabled
on ingress objects. This means TLS will only be disabled for ingress if
explicitly defined as such.
Fixes https://github.com/humio/humio-operator/issues/216

Allow disabling TLS for ingress.

---

api/v1alpha1/humiocluster_types.go
charts/humio-operator/templates/crds.yaml
config/crd/bases/core.humio.com_humioclusters.yaml
controllers/humiocluster_controller_test.go
controllers/humiocluster_defaults.go
controllers/humiocluster_services.go

Allow the user to define a custom set of annotations that should be
added to the service object pointing to the Humio pods.
The main benefit here is that you could run setups where you offload TLS
termination entirely to e.g. AWS NLB's without requiring the use of an
ingress controller.
Fixes https://github.com/humio/humio-operator/issues/215

Support user-defined service annotations.

---

config/samples/core_v1alpha1_humiocluster_shared_serviceaccount.yaml
hack/test-helm-chart-kind-shared-serviceaccount-linkerd.sh

This PR adds a test script and sample `HumioCluster` with `linkerd` proxy injection using `podAnnotations` and a shared `ServiceAccount`. 
The script simulates the manual creation of resources when opting out of the service account per container setup and setup of linkerd in a kind cluster.

Add test script with shared ServiceAccount and linkerd proxy injection

---

controllers/humiocluster_controller_test.go
controllers/humiocluster_pods.go

Fixes https://github.com/humio/humio-operator/issues/234.

Only rely on zookeeper for node UUIDs when using ephemeral storage

---

controllers/humiocluster_controller.go
go.mod
go.sum
images/helper/go.mod
images/helper/go.sum
images/helper/main.go
pkg/helpers/clusterinterface.go
pkg/helpers/clusterinterface_test.go
pkg/humio/client.go
pkg/humio/client_mock.go

This is mostly in preparation for a new feature. The new feature allows us to rotate the API token for a given user ID and is being introduced in https://github.com/humio/cli/pull/49
Main two changes are:
- The `Address` in the `humioapi.Config{}` was changed from `string` to `*url.URL`
- `NewClient()` no longer returns an error

Upgrade dependency on Humio Go client

---

controllers/humiocluster_controller_test.go

Tests print out the latest `By()` so adding them different places makes
error messages much more clear.

Improve output on failed tests.

---

api/v1alpha1/humiocluster_types.go
charts/humio-operator/templates/crds.yaml
config/crd/bases/core.humio.com_humioclusters.yaml
controllers/humiocluster_controller.go
controllers/humiocluster_controller_test.go
controllers/humiocluster_defaults.go
controllers/humiocluster_pods.go

This is useful when you are hosting a local container image registry.
Fixes https://github.com/humio/humio-operator/issues/258

Add HelperImage option to allow user-defined helper images.

---

controllers/humiocluster_controller_test.go
controllers/humiocluster_defaults.go
controllers/humiocluster_version.go

I did run the tests locally where I bumped the default Humio container image tag to 1.17.0, which worked just fine, but I'm guessing we want to stick with our stable releases as the default version.
Also, not sure what to do about the constants at this point. Right now the helper image only contains one package, which I can't import, so we'd need to split that up if we want to keep the constants in a separate package. If we split such things out, we may also want to refactor the other couple of things we have layout around which also has a copy in the main project as well as the helper image project.

Validate API token is obtained using the expected methods

---

Makefile

This only affects the test cases where we don't spin up real containers.
Looks like it cuts down the test time with ~1 minute. Not a big difference, but we might as well do it anyways.
https://github.com/humio/humio-operator/actions?query=workflow%3ACI

CI: Run tests in parallel

---

controllers/humioresources_controller_test.go

This doesn't fail when using a "new/empty" Kubernetes cluster when running the e2e tests because we typically start from scratch for every e2e test run.
I noticed this issue while trying to run the e2e tests a second time on the same `kind` cluster.

Test for HumioView should also clean up repository

---

controllers/humiocluster_controller_test.go
controllers/suite_test.go

Without this, if you run the tests in parallel you often end up with
problems where one test finishes early and then the teardown of that
will remove other tests running in parallel.
This is not a problem for our e2e tests yet, as they right now still run
sequentially, but this is part of what is required to make it possible
to run the e2e tests in parallel.

Set cleanup annotation on a per-test-process to prevent conflicts when running in parallel.

---

Makefile

Also, add a new test target to run tests until they fail.
I've used this new target locally with 40+ iterations without issues.

Randomize specs when running CI tests.

---

controllers/humiocluster_controller_test.go
controllers/humiocluster_defaults.go

For existing clusters using this in combination with persistent disks,
they will continue to work as they will reuse the existing node UUID
file from the persistent disk. This means that no changes are required
by the user here even if the default behaviour changes slightly.

Only leverage Zookeeper to obtain node UUID when using ephemeral disks

---

.github/action/operator-sdk/Dockerfile
.github/workflows/chart-lint.yaml
Makefile
hack/install-e2e-dependencies.sh

Remove unused tools from operator-sdk action.
We've migrated our GitHub Action workflows to run helm/kubectl/etc.
directly from the shell in our workflows instead of running it inside
the operator-sdk action container due to connectivity complications.
Because of this, we already migrated away from using the tools in this
way and is safe to remove. Right now we don't use the operator-sdk
action at all, but we do have a few disabled workflow steps that uses
it, which is why I'm not deleting the action entirely.

Bump to operator-sdk 1.3.0, kustomize 3.8.7 and helm 3.4.2.

---

config/samples/core_v1alpha1_humiocluster.yaml
config/samples/core_v1alpha1_humiocluster_shared_serviceaccount.yaml
controllers/humiocluster_controller.go
controllers/humiocluster_controller_test.go
controllers/humiocluster_defaults.go
examples/humiocluster-affinity-and-tolerations.yaml
examples/humiocluster-nginx-ingress-with-cert-manager.yaml
examples/humiocluster-nginx-ingress-with-custom-path.yaml

Up until the default has been to EmptyDir. It is safer to require the
user to specify which type of storage they want to use. This should
help in scenarios where the user forgot to configure what type of
storage they want to use and thus unknowingly ended up using the
previous default.

Require explicitly defined storage configuration.

---

controllers/humiocluster_defaults.go
controllers/humiocluster_defaults_test.go
controllers/humiocluster_version.go

This will adjust how Humio logs and will help streamline the log formats used across our different logging methods, such as stdout, files and such.
Given the change to the logging format, any dashboards, alerts, etc. would need to be adjusted to work with the new format.

Use new logging format for Humio 1.20.1+

---

controllers/humiocluster_controller.go

Previously it would try to fetch the `Issuer` object to check if it should be cleaned up no matter if cert-manager is present or not. If cert-manager is not present, we will not be able to fetch the `Issuer` objects as the CRD will not be present.
Related to https://github.com/humio/humio-operator/issues/358

Only try to cleanup CA Issuer if cert-manager is present.

---

controllers/humioaction_annotations.go
controllers/humioaction_controller.go
controllers/humioalert_annotations.go
controllers/humioalert_controller.go
controllers/humiocluster_controller.go
controllers/humiocluster_controller_test.go
controllers/humiocluster_persistent_volumes.go
controllers/humiocluster_pods.go
controllers/humiocluster_secrets.go
controllers/humiocluster_status.go
controllers/humiocluster_tls.go
controllers/humioexternalcluster_controller.go
controllers/humioingesttoken_controller.go
controllers/humioparser_controller.go
controllers/humiorepository_controller.go
controllers/humioresources_controller_test.go
controllers/humioview_controller.go
controllers/suite_test.go
images/helper/main.go
pkg/helpers/clusterinterface.go
pkg/helpers/clusterinterface_test.go
pkg/kubernetes/certificates.go
pkg/kubernetes/ingresses.go
pkg/kubernetes/persistent_volume_claims.go
pkg/kubernetes/pods.go

For test cases, we also create a single empty context in the beginning
and reuse that instead of creating an empty context over an over.

Use available context introduced after upgrading operator-sdk

---

controllers/humiocluster_controller.go
controllers/humiocluster_controller_test.go
pkg/humio/client_mock.go
pkg/humio/license.go

Humio's GraphQL API returns timestamps in RFC3339 format whereas
the actual license itself contains the timestamps in unix time.

Fix bug where license updates are triggered continuously

---

controllers/suite_test.go

`In Ginkgo 2.0 both RunSpecsWithDefaultAndCustomReporters and RunSpecsWithCustomReporters have been deprecated. Users must call RunSpecs instead.`
https://github.com/onsi/ginkgo/blob/v2/docs/MIGRATING_TO_V2.md#migration-strategy-2

Fix Ginkgo 2.0 deprecation warning

---

hack/run-e2e-tests-crc.sh
hack/run-e2e-tests-kind.sh

This means `ginkgo` command will be the last command and will thus
dictate what the exit code of the script will be. The exit code of the
script is what indicates whether the e2e test suite passed or not.

Use shell trap to cleanup Telepresence components

---

controllers/humioaction_controller.go
controllers/humioalert_controller.go
controllers/humiocluster_controller.go
controllers/humioexternalcluster_controller.go
controllers/humioingesttoken_controller.go
controllers/humioparser_controller.go
controllers/humiorepository_controller.go
controllers/humioview_controller.go
controllers/suite_test.go
main.go
pkg/helpers/helpers.go

Here's a snippet that shows the new format in top and the old ones in the bottom:

Use RFC3339 format for operator log timestamps

---

controllers/humiocluster_controller.go
controllers/humiocluster_status.go

Status updates trigger reconciliation, so we should only update the status if it has changed.
The reason I changed `setLicense()` to return an `error` is to keep things consistent with the other methods setting status.

Only set license status if it has changed

---

.github/workflows/master.yaml
.github/workflows/release-container-helperimage.yaml
.github/workflows/release-container-image.yaml
Dockerfile
Makefile
controllers/humiocluster_status.go
controllers/suite_test.go
go.mod
go.sum
images/helper/Dockerfile
images/helper/go.mod
images/helper/go.sum
images/helper/main.go
main.go
pkg/humio/client.go

This sets the `User-Agent` header as follows:
- Helper image: `humio-operator-helper/$VERSION ($COMMIT on $DATE)`
- Operator image: `humio-operator/$VERSION ($COMMIT on $DATE)`
This makes it easier to track what specific implementations are in use.

Set custom user agent headers

---

images/helper/version.go

Noteworthy changes:
- Set more detailed version information when building the container image.
- Drop support for Humio version prior to 1.17.0 and clean up logic related to these older versions.

helper: Release 0.3.0

---

charts/humio-operator/Chart.yaml
charts/humio-operator/values.yaml
config/crd/bases/core.humio.com_humioactions.yaml
config/crd/bases/core.humio.com_humioalerts.yaml
config/crd/bases/core.humio.com_humioclusters.yaml
config/crd/bases/core.humio.com_humioexternalclusters.yaml
config/crd/bases/core.humio.com_humioingesttokens.yaml
config/crd/bases/core.humio.com_humioparsers.yaml
config/crd/bases/core.humio.com_humiorepositories.yaml
config/crd/bases/core.humio.com_humioviews.yaml

Depends on: https://github.com/humio/humio-operator/pull/397
Note: Tests needs to be rerun after we have cut the new release of the helper image.

Release Helm chart 0.9.0

---

hack/install-e2e-dependencies.sh

For now, I've stuck with the version matching the `kindest/node` container image used when spinning up the `kind` cluster.

Install kubectl as e2e dependency

---

Makefile
README.md
hack/install-e2e-dependencies.sh
hack/install-helm-chart-dependencies-kind.sh
hack/preload-images-kind.sh
hack/run-e2e-tests-crc.sh
hack/run-e2e-tests-kind.sh
hack/run-e2e-tests-using-kubectl-kind.sh
hack/start-kind-cluster.sh
hack/test-helm-chart-crc.sh
test.Dockerfile

Instead we run a pod inside the `kind` cluster with the source code and
tools to compile and run the tests inside the cluster itself.
This unfortunately means the tests using `crc` for testing will not
work. We use `kind load docker-image` to load the container where the
tests will be performed within and `crc` doesn't have a similar command.
This means that the `crc` scripts will likely need to either push the
containers to a remote registry, or potentially "docker push" the image
directly to a registry running inside the `crc` cluster.

Stop using Telepresence to run E2E tests

---

controllers/humiocluster_controller.go
controllers/humiocluster_controller_test.go
controllers/humiocluster_ingresses.go
pkg/kubernetes/ingresses.go

Fixes #414 
Kubernetes v1.22 completely removes networking/v1beta1 which has been
available from Kubernetes v1.19 according to:
https://kubernetes.io/docs/reference/using-api/deprecation-guide/

Use networking/v1 instead of networking/v1beta1

---

controllers/humiocluster_controller.go

Without this, the Humio client config might point to a different
HumioCluster/HumioExternalCluster resource, from the previous
reconciliation.

Update Humio client config before validating/installing license

---

controllers/humioaction_controller.go
controllers/humioalert_controller.go
controllers/humiocluster_controller.go
controllers/humioexternalcluster_controller.go
controllers/humioingesttoken_controller.go
controllers/humioparser_controller.go
controllers/humiorepository_controller.go
controllers/humioview_controller.go
controllers/suite_test.go
main.go

This together with function names and caller line numbers makes it easy
to know exactly where things are originating from.

Create a single base logger and attach version information to log entries

---

.github/workflows/codeql-analysis.yml

This fixes the following warning:
<quote>
Analyze (go)
1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
</quote>

Fix CodeQL github action workflow warning

---

go.mod
go.sum

This cherry-picks the humio api update from https://github.com/humio/humio-operator/pull/440 since that one is inconsistently passing/failing tests and I need to troubleshoot it. This should at least get us the timeout which is a less risky change.

Upgrade humio cli dep to 0.28.7

---

controllers/humiocluster_defaults.go
controllers/humiocluster_pods.go
go.mod

This also moves the image pull policy default logic to separate function.
Moving this makes it more consistent with the other default functions we
already have in place.

Print pod spec diff when pods don't match

---

controllers/humiocluster_controller.go
controllers/humiocluster_pod_status.go

With this change we only print cluster node details once per reconcile
and also combine the log statements in getPodsStatus to a single log
entry.

Move log statements around to lower amount of log entries

---

pkg/humio/client.go

We introduced this in https://github.com/humio/humio-operator/pull/467
but I only added this for insights while I was debugging things. I don't
think we should keep it around.

Clean up log entry

---

controllers/humiocluster_controller.go
controllers/humioexternalcluster_controller.go
controllers/humioingesttoken_controller.go
controllers/humioparser_controller.go
controllers/humiorepository_controller.go
controllers/humioview_controller.go

https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/reconcile/reconcile.go#L28-L33

No need to specify Requeue if RequeueAfter is already specified

---

controllers/humioview_controller.go
controllers/humioview_controller_test.go

Currently if a view has multiple connections Kubernetes might return the
connection slice in different orders every time. As we compare view connections
with a reflect.DeepEqual that results in updates to views over and over again.
When ever a view is updated in Humio any live queries are refreshed which leads
to flashing dashboards.
This change introduces a mitigation to this behaviour by sorting the existing
and new connection slices before comparing them. This way we only update the
view in Humio if the functional behaviour has changed.

Sort view connections before comparing

---

controllers/humiocluster_controller.go
controllers/humiocluster_defaults.go
controllers/humiocluster_pods.go
controllers/humiocluster_status.go
controllers/suite_test.go
pkg/helpers/helpers.go
pkg/humio/client.go
pkg/humio/client_mock.go

Removes ~25% of our use of `reflect.DeepEqual` outside our tests.

Various cleanup and removing some uses of reflect package

---

controllers/suite_test.go

Previously it didn't pass the check and thus didn't clean up etcd &
kube-apiserver when test suite was done. This meant that we ended up
leaving lots of etcd and kube-apiserver processes running when running
"make test".

Fix AfterSuite so it cleans up the testenv when test suite is done

---

images/helper/main.go

We don't need to read the global snapshot file anymore, so there's no
need to wait for it to exist. At this point we only rely on the local
admin token in combination with the Humio API to get an API token for
the operator to use.

helper: Don't wait for global snapshot file

---

controllers/humioparser_controller.go
controllers/humiorepository_controller.go
controllers/humioview_controller.go

Fixes an issue where if a humio resource such as a repo is created before the cluster is ready, the resource will fail to be created and not retry until the operator is restarted. This will force a retry after 15 seconds.

Retry failed reconciles when managing humio resources

---

controllers/humiocluster_controller_test.go

Fixes one of the flaky tests. We check after deleting a label, but this is a race with the controller adding it back so it sometimes fails.

Fix flaky test

---

.github/workflows/ci.yaml
Makefile
controllers/humiocluster_controller_test.go
controllers/humiocluster_defaults_test.go
controllers/humioresources_controller_test.go
controllers/suite_test.go
go.mod
go.sum
hack/run-e2e-tests-crc.sh
hack/run-e2e-tests-kind.sh

https://onsi.github.io/ginkgo/MIGRATING_TO_V2
`
With the release of Ginkgo 2.0 the 1.x version is formally deprecated and no longer supported. All future development will occur on version 2.
`

Upgrade to ginkgo v2

---

charts/humio-operator/templates/operator-deployment.yaml
charts/humio-operator/values.yaml

Allow specifying annotations for the humio operator pod through values file.
Prometheus server requires pods to be annotated like below to scrape metrics automatically. The ServiceMonitor CR is only supported by prometheus operator.
```
prometheus.io/scrape: 'true'
prometheus.io/port: '9102'
```
Signed-off-by: Jayadeep KM <kmjayadeep@gmail.com>

Support podAnnotations in humio operator helm charts 

---

controllers/suite/clusters/suite_test.go
controllers/suite/resources/suite_test.go

Right now we end up logging everything 3 times, which isn't exactly what
we want. The idea was to make it easy to go from test result to related
log lines, but we shouldn't do that by duplicating all logs.
This disables the 2 additional copies so we only have one copy of
stdout. This does however mean we won't have a direct link from the test
report being logged out to the relevant log entries, but perhaps we can
find another solution to that.

Disable logging stdout from reports

---

images/helper/main.go

We've seen a few cases where the auth sidecar ends up continuously rotating the API token, which isn't what we want. The problem seems to be that we end up determining that the api token we try to validate is not valid, and thus rotate it over and over. Logs indicate that `getApiTokenForUserID` returns an error even if Humio logs indicate that the api token was rotated. To make this more clear, this includes information about what error happened when we try to rotate the api token, and also a few log statements to help understand when we flip between using the different API tokens.

helper: Improve logging

---

charts/humio-operator/templates/operator-rbac.yaml

If `operator.watchNamespaces` is not empty the operator-rbac.yaml has a `range` template for each namespace. The variables inside are scoped to the `watchNamespaces` variable rather than the root which causes exceptions from the Go parser.
Error: template: humio-operator/templates/operator-rbac.yaml:100:14: executing "humio-operator/templates/operator-rbac.yaml" at <.Values.operator.rbac.allowManageRoles>: can't evaluate field Values in type interface {}

Anchor variables to root scope in range template

---

.github/workflows/master.yaml
Dockerfile
Makefile
images/helper/Dockerfile

This helps cut down binary sizes. Quick tests showed the operator binary
drop from 48 MB to 35 MB.

Disable symbol table and DWARF generation

---

charts/humio-operator/templates/crds.yaml
charts/humio-operator/values.yaml
hack/gen-crds.sh
hack/test-helm-chart-crc.sh
hack/test-helm-chart-kind-shared-serviceaccount-linkerd.sh
hack/test-helm-chart-kind.sh

Helm3 creates CRD records first which can be skipped using --skipCRDs flag the current method used in the helm chart is based on a defunct Helm2 best practice
Signed-off-by: Ryan Faircloth <ryan@dss-i.com>

feat: Use Helm 3 best practice for CRD creation

---

api/v1alpha1/humioview_types.go
charts/humio-operator/templates/crds.yaml
config/crd/bases/core.humio.com_humioviews.yaml
config/samples/core_v1alpha1_humioview.yaml
controllers/humioview_controller.go
controllers/humioview_controller_test.go
pkg/humio/client.go

Signed-off-by: Nam Hai Nguyen <namhai.nguyen-ext@commercetools.com>
I'd like to use Humio operator to change a view's description. This action should be similar to changing a repo's description.

Allow to change view's description

---

api/v1alpha1/humioview_types.go
charts/humio-operator/templates/crds.yaml
config/crd/bases/core.humio.com_humioviews.yaml
config/samples/core_v1alpha1_humioview.yaml
controllers/humioview_controller.go
controllers/humioview_controller_test.go
pkg/humio/client.go

Reverts humio/humio-operator#582
There is no view field on the humio client api so this does not work.

Revert "Allow to change view's description"

---

.github/workflows/e2e.yaml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Remove deprecated action function

---

controllers/humiocluster_defaults.go

original names "init" and "auth" are generic its common to prefer names that a unique and meaningful.

feat: Change container names in pod

---

.github/workflows/codeql-analysis.yml

https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/

Bump codeql actions

---

.github/workflows/e2e.yaml
hack/start-kind-cluster.sh

I'm guessing we're going to stick with the current k8s minor versions for now, and whenever we feel like it, we can enable k8s 1.25. I did update one of the shell scripts to k8s 1.25 though, but those don't run on CI. I'm guessing its fine to start moving towards testing against k8s 1.25

Bump kind v0.14.0 -> v0.16.0

---

charts/humio-operator/templates/operator-deployment.yaml
charts/humio-operator/templates/operator-rbac.yaml
controllers/humiocluster_defaults.go
controllers/suite/clusters/suite_test.go
controllers/suite/resources/suite_test.go

It is possible some injected containers may require root move this setting to the humio-operator container

fix: runAsNonRoot should be container specific not pod

---

charts/humio-operator/templates/operator-deployment.yaml

There is a duplicate value "runAsNonRoot: true" in the latest release.

remove duplicate value in operator deploy

---

config/samples/core_v1alpha1_humiocluster.yaml
config/samples/core_v1alpha1_humiocluster_shared_serviceaccount.yaml
controllers/humiocluster_defaults.go
controllers/humiocluster_defaults_test.go
controllers/humiocluster_pods.go
controllers/humiocluster_version.go
controllers/suite/clusters/humiocluster_controller_test.go
controllers/suite/common.go
examples/humiocluster-affinity-and-tolerations.yaml
examples/humiocluster-data-volume-persistent-volume-claim-policy-kind-local.yaml
examples/humiocluster-ephemeral-with-gcs-storage.yaml
examples/humiocluster-ephemeral-with-s3-storage.yaml
examples/humiocluster-kind-local.yaml
examples/humiocluster-multi-nodepool-kind-local.yaml
examples/humiocluster-nginx-ingress-with-cert-manager.yaml
examples/humiocluster-nginx-ingress-with-custom-path.yaml
examples/humiocluster-nginx-ingress-with-hostname-secrets.yaml
examples/humiocluster-persistent-volumes.yaml

Previously we always added `ZOOKEEPER_URL_FOR_NODE_UUID` when running with `USING_EPHEMERAL_DISKS=true` but as of version 1.70.0, we don't need to leverage zookeeper anymore for determining node UUID's. Because we always added the `ZOOKEEPER_URL_FOR_NODE_UUID` option, this meant that adding `ZOOKEEPER_URL` was required by the user.
Instead of always adding the option when using `USING_EPHEMERAL_DISKS=true`, this changes it so that it also requires `ZOOKEEPER_URL` set, which the user explicitly had to set previously, but with this change it is possible to leave out `ZOOKEEPER_URL` which means the operator will not automatically add `ZOOKEEPER_URL_FOR_NODE_UUID` and thus switch away from using zookeeper to determine node UUID's.
This effectively means users that are running with …

Change behavior of when we automatically append ZOOKEEPER_URL_FOR_NODE_UUID config

---

controllers/humiocluster_defaults.go
controllers/humiocluster_version.go
examples/humiocluster-data-volume-persistent-volume-claim-policy-kind-local.yaml
examples/humiocluster-kind-local.yaml
examples/humiocluster-multi-nodepool-kind-local.yaml

From 1.68.0 the default is now single-user auth, so there's no need to explicitly set it in the operator code base.
https://library.humio.com/falcon-logscale/release-notes-all.html#release-notes-all-1-68-0
I'm also removing the auth env vars from the examples as they don't seem relevant for what the examples are trying to show.

Only append AUTHENTICATION_METHOD for versions prior to 1.68.0

---

config/samples/core_v1alpha1_humiocluster.yaml
config/samples/core_v1alpha1_humiocluster_shared_serviceaccount.yaml
controllers/humiocluster_defaults.go
controllers/humiocluster_pod_lifecycle.go
controllers/humiocluster_pods.go
controllers/humiocluster_version.go
controllers/suite/clusters/humiocluster_controller_test.go
examples/humiocluster-affinity-and-tolerations.yaml
examples/humiocluster-data-volume-persistent-volume-claim-policy-kind-local.yaml
examples/humiocluster-ephemeral-with-gcs-storage.yaml
examples/humiocluster-ephemeral-with-s3-storage.yaml
examples/humiocluster-kind-local.yaml
examples/humiocluster-multi-nodepool-kind-local.yaml
examples/humiocluster-nginx-ingress-with-cert-manager.yaml
examples/humiocluster-nginx-ingress-with-custom-path.yaml
examples/humiocluster-nginx-ingress-with-hostname-secrets.yaml
examples/humiocluster-persistent-volumes.yaml

This also adds update strategy to a test, since the default is `HumioClusterUpdateStrategyReplaceAllOnUpdate` but the test seems to be trying to test the behavior of `HumioClusterUpdateStrategyRollingUpdateBestEffort` and thus is the cause of a bunch of flakiness.

Get rid of preview/stable logic for RollingUpdateBestEffort

---

charts/humio-operator/Chart.yaml
charts/humio-operator/templates/_helpers.tpl
charts/humio-operator/templates/operator-deployment.yaml
charts/humio-operator/templates/operator-rbac.yaml
charts/humio-operator/templates/operator-service.yaml
charts/humio-operator/templates/operator-servicemonitor.yaml

1. Refactor common labels with the `_helper.tpl` template
2. Allows us to set extra labels in `commonLabels`. Those labels would be propagated to all k8s objects (as the name implies, they are "labels common to all objects".
3. This does not mess with the `Selector` on the k8s service object so there's no breaking change.
When doing `helm diff` I notice the following:
* there was some generic/common labels missing on the k8s `ServiceMonitor` and `Service` objects. This PR would add them. Here in for the svc:
```diff
logging, humio-operator, Service (v1) has changed:
...
labels:
app: 'humio-operator'
app.kubernetes.io/name: 'humio-operator'
app.kubernetes.io/instance: 'humio-operator'
+     app.kubernetes.io/managed-by: 'Helm'
+     helm.sh/chart: 'humio-operator-0.18.0'
spec:
ports:
``` …

refactor common labels and new feature set additionnal common labels

---

api/v1alpha1/humiocluster_types.go
api/v1alpha1/zz_generated.deepcopy.go
charts/humio-operator/crds/core.humio.com_humioclusters.yaml
charts/humio-operator/templates/operator-deployment.yaml
charts/humio-operator/values.yaml
config/crd/bases/core.humio.com_humioclusters.yaml
controllers/humiocluster_defaults.go
controllers/humiocluster_pods.go
controllers/suite/clusters/humiocluster_controller_test.go

Feature Request: Support admin defined affinity and tolerations - source @ryanfaircloth
Moves the static affinity to values.yaml as the default to avoid breakage and correctly combines the requirements so arm64 and ppc nodes can not be selected.
Feature Request: Add TopologySpreadConstraints support to the humiocluster CRD - source @ryanfaircloth 
This PR fixes #342 with the addition of TopologySpreadConstraints to the CR. Node instances of operator deployed by helm will not automatically update the CR for those instances the CR must be applied manually

Features: Configurable affinity, tolerations, and topology constraints

---

api/v1alpha1/humiocluster_types.go
charts/humio-operator/crds/core.humio.com_humioclusters.yaml
config/crd/bases/core.humio.com_humioclusters.yaml
controllers/humiocluster_controller.go
controllers/humiocluster_defaults.go
controllers/humiocluster_pods.go
controllers/suite/clusters/humiocluster_controller_test.go
pkg/kubernetes/configmaps.go

This replaced the even older view-group-permissions.json file years ago.
Official docs on the feature: https://library.humio.com/falcon-logscale/security-authorization-roles-in-file.html
---
Given how long time ago the old format was replaced, perhaps we could even consider removing support for that soon.

Add support for role-permissions.json file

---

controllers/humiocluster_controller.go

Due to the size of the details for large clusters, this ends up being split into multiple log lines causing log shipping to ship the log line as multiple events, which breaks parsing of each event since they are not valid JSON events.
So far, we've not had a case where this log line was important to us, so let's remove it.

Stop printing node details for all cluster nodes

---

api/v1alpha1/humiocluster_types.go
charts/humio-operator/crds/core.humio.com_humioclusters.yaml
config/crd/bases/core.humio.com_humioclusters.yaml
controllers/humiocluster_defaults.go
controllers/humiocluster_defaults_test.go
controllers/humiocluster_pods.go
controllers/humiocluster_version.go
controllers/suite/clusters/humiocluster_controller_test.go

This stops automatically appending `ZOOKEEPER_PREFIX_FOR_NODE_UUID` and `ZOOKEEPER_URL_FOR_NODE_UUID` if the user configured environment variables to contain`USING_EPHEMERAL_DISKS=true` and some value for `ZOOKEEPER_URL`.
Given the scenario described above, the list of environment variables for pods will be different, and thus pods will be replaced when upgrading the operator to a version that includes these changes.

Skip ZK node UUID URL for new logscale versions

---

charts/humio-operator/templates/operator-deployment.yaml

[nodeSelector](https://github.com/humio/humio-operator/blob/fac3ed3b75de8f77262dbf5e7efcf5d216825ac0/charts/humio-operator/values.yaml#L24C5-L24C5) is mentioned in values file, but in deployment template nodeSelectors is required. Small fix to unify naming with k8s.

nodeSelector fix

---

go.mod

We no longer depend on the module

Remove unused replace in go.mod

---

api/v1alpha1/humiocluster_types.go
controllers/humiocluster_pod_lifecycle.go

This is the default update strategy, but without this it means even if ReplaceAllOnUpdate is explicitly configured and there's only pending config changes for rollout, then we likely still do rolling update, which is not the desired behavior.

Replace all if ReplaceAllOnUpdate strategy is set

---

go.mod
go.sum
pkg/humio/client.go

View connections need to have a different data type to allow multiple filters for a single repository.
This change requires humio/cli#138 to be merged and a new version of the module created. Fixes #745.

Allow creating/updating View connections with multiple filters per repo

---

Makefile

By default, we only install it if the binary is missing, but recently we updated it and started seeing issues with some clients using the old version while others use the new one. To fix this, we make sure to always fetch the desired version.

Always install desired version of controller-gen

---

controllers/suite/clusters/humiocluster_controller_test.go

With this, it means we can get https://github.com/humio/humio-operator/blob/master/.github/workflows/preview.yaml going and test against newer versions

Pin versions for upgrade tests

---

pkg/helpers/clusterinterface.go
pkg/helpers/clusterinterface_test.go
pkg/humio/client.go
pkg/humio/client_mock.go

Improve the reliability of communications between the operator and the cluster by using the ClusterIP svc rather than the headless service. When NodeDNS cache is enabled this avoids stale nodes and allows the cluster to manage which pods are considered based on ready status

fix: use ClusterIP rather than headless service operator client

---

pkg/helpers/clusterinterface.go
pkg/helpers/clusterinterface_test.go
pkg/humio/client.go
pkg/humio/client_mock.go

This reverts commit 0c96b65c6482442210e0eda91fd79c914362b62b.

Revert "fix: use ClusterIP rather than headless service operator client"

---

.github/workflows/master.yaml

This only builds and pushes for master builds. Once confirmed working, we can adjust the release GitHub Action workflows to also include this.

Build and push master arm64 helper image

---

controllers/suite/clusters/humiocluster_controller_test.go

We have seen flakiness due to the pods being deleted so fast after manually marking them unschedulable, that the ListPods never gets to see the unschedulable pods.

test: Skip looking for unschedulable pods when running with envtest.

---

controllers/humioaction_controller.go
controllers/humioaggregatealert_controller.go
controllers/humioalert_controller.go
controllers/humiocluster_pods.go
controllers/humiofilteralert_controller.go
controllers/humioingesttoken_controller.go
controllers/humioparser_controller.go
controllers/humiorepository_controller.go
controllers/humioscheduledsearch_controller.go
controllers/humioview_controller.go
internal/helpers/helpers.go

With this change, the key-value diff pairs are nested into a `diff` field on the root logger. Previously, each key would be its own field on the root, making it not obvious which fields were related to diff.

Refactor diff field

---

charts/humio-operator/templates/operator-deployment.yaml
charts/humio-operator/values.yaml

With this change, we don't need to remember to update the values.yaml file when we publish new builds.

helm: Update Deployment to use appVersion from Chart.yaml by default

---

charts/humio-operator/templates/operator-rbac.yaml

Without this change, the operator is unable to access those resources and spits out errors like so:
```
W0212 08:06:36.849355       1 reflector.go:539] pkg/mod/k8s.io/client-go@v0.29.7/tools/cache/reflector.go:229: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:default:foo" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
E0212 08:06:36.849440       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.29.7/tools/cache/reflector.go:229: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:serviceaccount:default:foo" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
```

fix: Add missing PodDisruptionBudget to the Role/ClusterRole

---

controllers/humiocluster_controller.go

This change means we'll only pin a non-empty zone going forward, and if no zone information is available it'll behave as it did previously assuming update strategy uses the default MaxUnavailable value of 1.
Fixes https://github.com/humio/humio-operator/issues/910

Fix issue where HumioClusterReconciler is stuck pinning an empty zone

---

api/v1alpha1/humiorepository_types.go
charts/humio-operator/crds/core.humio.com_humiorepositories.yaml
config/crd/bases/core.humio.com_humiorepositories.yaml
docs/api.md

Fixes #925 
ingestSizeInGB and storageSizeInGB are currently defined with a minimum of 1. However the value of 0 is required to leave these as unlimited and to only use the timeInDays limits.
Changing this to 0 fixes this issue.

Allow unlimited sizes in HumioRepository

---

api/v1alpha1/humiobootstraptoken_types.go
charts/humio-operator/crds/core.humio.com_humiobootstraptokens.yaml
config/crd/bases/core.humio.com_humiobootstraptokens.yaml
docs/api.md
internal/controller/humiobootstraptoken_controller.go
internal/controller/humiobootstraptoken_defaults.go
internal/controller/humiobootstraptoken_pods.go
internal/controller/suite/clusters/humiocluster_controller_test.go
internal/controller/suite/common.go

Fixes [883](https://github.com/humio/humio-operator/issues/883).

Add ability to use bootstrap tokens from image secrets

---

Makefile
cmd/main.go
internal/controller/common.go
internal/controller/humioaction_controller.go
internal/controller/humioaggregatealert_controller.go
internal/controller/humioalert_controller.go
internal/controller/humiobootstraptoken_controller.go
internal/controller/humiocluster_controller.go
internal/controller/humiocluster_status.go
internal/controller/humioexternalcluster_controller.go
internal/controller/humiofilteralert_controller.go
internal/controller/humioingesttoken_controller.go
internal/controller/humioparser_controller.go
internal/controller/humiorepository_controller.go
internal/controller/humioscheduledsearch_controller.go
internal/controller/humioview_controller.go
internal/controller/suite/clusters/suite_test.go
internal/controller/suite/resources/suite_test.go

This flag allows operators to manage the default requeue period of the Humio* CRs managed. In deployments where there are sufficient role restrictions it should be possible to prevent competing changes to Logscale entities via the web interface or other GraphQL clients. Thus the requeue period does not need to be such a short period.
Replaces: #960 (this PR takes the original contribution and solves the warning from the linter)
Resolves: #956

Add requeue-period flag.

---

internal/api/humiographql/graphql/repositories.graphql
internal/api/humiographql/humiographql.go
internal/humio/client.go

basically title, actually uses the retention parameters if any is provided from the k8s resource.
I intentionally broke it out to a separate API in the client, `CreateRepositoryWithRetention`, to minimize potential impact to any existing users. It does use the same underlying GraghQL API `createRepository` as the existing one though. LMK if you would prefer to just expand the existing GQL there!
`make test` passes locally.

CreateRepository actually uses the retention parameters if provided

---

Dockerfile
Makefile
hack/functions.sh
hack/run-e2e-using-kind-dummy.sh
hack/run-e2e-using-kind.sh
hack/start-kind.sh
hack/stop-kind.sh
images/helper/Dockerfile
images/logscale-dummy/Dockerfile

- ensure Makefile `docker build` commands have the same format
- update kind / kubectl versions
- run docker login only if dependencies are in place
- ensure same FROM golang:1.23.6-alpine used across

Small fixes to prep for migration
